Repository wecode-bootcamp-korea/39-2nd-Just-We-Air-frontend, pull requests merged in 2022-12, with the labels that each got.

#4 [39기 남연우] ADD: 카카오 간편 로그인 레이아웃 & 기능 구현 완료
  public/images/Login/apple.png
  public/images/Login/kakao.png
  public/images/Login/naver.png
  src/Router.js
  src/pages/Login/KakaoAuth.js
  src/pages/Login/Login.js
  src/pages/Login/RedirectHandler.js
  src/pages/Login/Spinner.js
Labels: 멘토 리뷰 요청, 완료

#5 [39기 오주형] Modify: update README.md
  README.md
Labels: 멘토 리뷰 요청

#9 [39기 남연우] ADD: 회원가입 레이아웃 & 기능 구현 완료
  package-lock.json
  public/images/SignUp/apple.png
  public/images/SignUp/kakao.png
  public/images/SignUp/lock.png
  public/images/SignUp/minor.png
  public/images/SignUp/naver.png
  public/images/SignUp/phone.png
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/RedirectHandler.js
  src/pages/SignUp/SignUp.js
Labels: 수정 요청

#12 [39기 남연우] ADD : 토스결제 기능 구현&레이아웃 완료
  .gitignore
  package-lock.json
  package.json
  public/data/orderdata.json
  public/images/Toss.png
  public/images/kakaopay.png
  public/images/naverpay.png
  public/images/orange.png
  public/images/paypal-logo.png
  public/images/samsungpay.png
  public/images/unionpay.png
  public/images/wechatpay.png
  src/config.js
  src/pages/Payment/Payment.js
  src/pages/Payment/PaymentSuccess.js
Labels: 수정 요청

#2 [39기 천정환] ADD:TAB 메뉴, 날짜 레이아웃 백엔드 통신, conflict 해결 및 Rebase 완료
  package-lock.json
  package.json
  public/images/Fukuoka.jpeg
  public/images/Gaum.png
  public/images/Team.jpg
  public/images/Tokyo.jpeg
  public/images/arrow.png
  public/images/cheon.jpg
  public/images/cheon1.jpg
  public/images/dateIcon.png
  public/images/jeju.jpeg
  public/images/nam1.jpg
  public/images/nam2.jpg
  public/images/nam3.jpg
  public/images/next-arrow.svg
  public/images/ohju.jpg
  public/images/ohju1.jpg
  public/images/osaka.jpeg
  public/images/prev-arrow.svg
  public/images/song3.jpeg
  public/images/song5.jpeg
  public/images/yeongs.jpg
  public/images/yeongs1.jpg
  src/Router.js
  src/pages/Main/Main.css
  src/pages/Main/Main.js
  src/pages/Main/component/Slide.js
  src/pages/Main/component/SlideSecond.js
  src/styles/theme.js
Labels: Conflict 해결 요청

#13 [39기 남연우] ADD: 결제 페이지 수정사항 반영
  src/pages/Payment/Payment.js
  src/pages/Payment/PaymentSuccess.js
Labels: 멘토 리뷰 요청

#1 [39기 천정환] ADD:윗상단 Nav바 레이아웃 수정완료
  src/components/Nav/Nav.js
Labels: 수정 요청
